using MonoSAMFramework.Portable.Localization;
using MonoSAMFramework.Portable.LogProtocol;

namespace SwitchGame.Shared.Resources
{
	/* This file was generated by a tool */
	public static class L10NImpl
	{
		public const int LANG_EN_US = 0;
		public const int LANG_DE_DE = 1;

		public const int LANG_COUNT = 2;

//-----------------------------------------------------------------------

		public const int STR_ERR_OUTOFMEMORY       = 0;
		public const int STR_ERR_SOUNDPLAYBACK     = 1;
		public const int STR_ERR_MUSICPLAYBACK     = 2;

		private const int TEXT_COUNT = 3; // = next idx

		public static void Init(int lang)
		{
			L10N.Init(lang, TEXT_COUNT, LANG_COUNT);

			// [en-US] [de-DE]

			// Description: Text of error toast. Is shown when the profile/level cuold not be saved because there is no free disk space
			// Usage:       MainGame.cs:184
			L10N.Add(STR_ERR_OUTOFMEMORY, "Saving failed: Disk full", "Speichern fehlgeschlagen: Speicher voll");

			// Description: Text of error toast. Is shown when the sound playback failed. Informs the user that the sound is now disabled until he manually enables them again
			// Usage:       SGSounds.cs:39
			L10N.Add(STR_ERR_SOUNDPLAYBACK, "Sound playback failed. Disabling sounds ...", "Soundwiedergabe fehlgeschlagen. Sounds werden deaktiviert ...");

			// Description: Text of error toast. Is shown when the music playback failed. Informs the user that the music is now disabled until he manually enables them again
			// Usage:       SGSounds.cs:51
			L10N.Add(STR_ERR_MUSICPLAYBACK, "Music playback failed. Disabling music ...", "Musikwiedergabe fehlgeschlagen. Musik wird deaktiviert ...");


			// [en-US] [de-DE]

#if DEBUG
			L10N.Verify();
#endif
		}
	}
}
